import React, { useState, useEffect, useCallback, useMemo } from "react";
import { useLocation, Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import billService from "../services/billService";
import { TableSkeleton } from "../components/common/Skeleton";
import Modal from "../components/common/Modal";
import EmptyState from "../components/common/EmptyState";
import {
  Search,
  Calendar,
  CreditCard,
  Eye,
  Printer,
  Milk,
  FilterX,
  ChevronLeft,
  ChevronRight,
  Plus
} from "lucide-react";

const Bills = () => {
  const { user } = useAuth();
  const { showError, showSuccess } = useToast();
  const location = useLocation();

  // Read optional URL search parameters (e.g. from Dashboard search action)
  const queryParams = useMemo(() => new URLSearchParams(location.search), [location.search]);
  const initialSearch = queryParams.get("search") || "";

  // Bills State
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);

  // Filters State
  const [search, setSearch] = useState(initialSearch);
  const [paymentMethod, setPaymentMethod] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [page, setPage] = useState(1);
  const limit = 10; // items per page

  // Invoice Detail Preview State
  const [selectedBill, setSelectedBill] = useState(null);
  const [isInvoiceOpen, setIsInvoiceOpen] = useState(false);

  // Load bills depending on user role
  const loadBills = useCallback(async () => {
    setLoading(true);
    try {
      let data = [];
      if (user.role === "admin") {
        data = await billService.getBills();
      } else {
        data = await billService.getBillsByAccountant(user._id);
      }
      setBills(data || []);
    } catch (err) {
      console.error(err);
      showError("Failed to fetch billing history log.");
    } finally {
      setLoading(false);
    }
  }, [user, showError]);

  useEffect(() => {
    loadBills();
  }, [loadBills]);

  // Sync search input if URL changes
  useEffect(() => {
    const s = queryParams.get("search");
    if (s) setSearch(s);
  }, [queryParams]);

  // Client-side filtering
  const filteredBills = useMemo(() => {
    return bills.filter((bill) => {
      // 1. Phone number filter
      if (search.trim() && !bill.customerNumber.includes(search.trim())) {
        return false;
      }
      // 2. Payment method filter
      if (paymentMethod && bill.paymentMethod !== paymentMethod) {
        return false;
      }
      // 3. Date range filter
      if (startDate) {
        const start = new Date(startDate);
        start.setHours(0, 0, 0, 0);
        if (new Date(bill.createdAt) < start) return false;
      }
      if (endDate) {
        const end = new Date(endDate);
        end.setHours(23, 59, 59, 999);
        if (new Date(bill.createdAt) > end) return false;
      }
      return true;
    });
  }, [bills, search, paymentMethod, startDate, endDate]);

  // Reset page when filters change
  useEffect(() => {
    setPage(1);
  }, [search, paymentMethod, startDate, endDate]);

  // Pagination slicing
  const paginatedBills = useMemo(() => {
    const startIdx = (page - 1) * limit;
    return filteredBills.slice(startIdx, startIdx + limit);
  }, [filteredBills, page, limit]);

  const totalPages = Math.ceil(filteredBills.length / limit) || 1;

  const handleClearFilters = () => {
    setSearch("");
    setPaymentMethod("");
    setStartDate("");
    setEndDate("");
  };

  const handleViewBill = (bill) => {
    setSelectedBill(bill);
    setIsInvoiceOpen(true);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div>
      {/* Title bar */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px", flexWrap: "wrap", gap: "12px" }}>
        <div>
          <h1 style={{ fontSize: "1.5rem", fontWeight: 700, color: "var(--color-text-primary)" }}>
            Billing Log History
          </h1>
          <p style={{ fontSize: "0.875rem", color: "var(--color-text-secondary)" }}>
            {user.role === "admin"
              ? "Track and audit store invoices across all accounts."
              : "Review invoices generated by your account."}
          </p>
        </div>

        <Link to="/bills/create" className="btn btn-success">
          <Plus size={18} />
          Create POS Bill
        </Link>
      </div>

      {/* Advanced Filtering controls */}
      <div className="card-panel" style={{ padding: "16px", marginBottom: "20px" }}>
        <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", alignItems: "center" }}>
          
          {/* Customer Phone Search */}
          <div className="search-input-wrapper" style={{ flexGrow: 1, maxWidth: "260px" }}>
            <Search size={14} className="search-icon" />
            <input
              type="text"
              placeholder="Search by customer phone..."
              className="form-input"
              style={{ padding: "6px 8px 6px 32px" }}
              value={search}
              onChange={(e) => setSearch(e.target.value.replace(/\D/g, ""))}
            />
          </div>

          {/* Payment Method Selector */}
          <div className="filter-group">
            <select
              value={paymentMethod}
              onChange={(e) => setPaymentMethod(e.target.value)}
              className="form-input"
              style={{ width: "140px", padding: "6px" }}
            >
              <option value="">All Payments</option>
              <option value="cash">Cash</option>
              <option value="card">Card</option>
              <option value="online">Online</option>
            </select>
          </div>

          {/* Date range inputs */}
          <div className="filter-group" style={{ display: "flex", gap: "6px", alignItems: "center" }}>
            <Calendar size={14} color="var(--color-text-secondary)" />
            <input
              type="date"
              className="form-input"
              style={{ width: "135px", padding: "6px" }}
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              title="Start Date"
            />
            <span style={{ color: "var(--color-text-secondary)" }}>to</span>
            <input
              type="date"
              className="form-input"
              style={{ width: "135px", padding: "6px" }}
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              title="End Date"
            />
          </div>

          {/* Clear Filters Button */}
          {(search || paymentMethod || startDate || endDate) && (
            <button
              onClick={handleClearFilters}
              className="btn btn-secondary btn-sm"
              style={{ display: "flex", gap: "4px", padding: "6px 12px", marginLeft: "auto" }}
            >
              <FilterX size={14} />
              Clear
            </button>
          )}

        </div>
      </div>

      {/* Main Table area */}
      {loading ? (
        <div className="card-panel">
          <TableSkeleton rows={limit} cols={7} />
        </div>
      ) : filteredBills.length === 0 ? (
        <EmptyState title="No Invoices Found" subtitle="No receipts match those query limits." />
      ) : (
        <div className="card-panel">
          <div className="table-wrapper">
            <table className="custom-table responsive-table">
              <thead>
                <tr>
                  <th>Invoice No.</th>
                  <th>Customer Phone</th>
                  <th>Total Amount</th>
                  <th>Payment Method</th>
                  <th>Accountant</th>
                  <th>Created Date</th>
                  <th style={{ textAlign: "center" }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {paginatedBills.map((bill) => (
                  <tr key={bill._id}>
                    <td data-label="Invoice No." style={{ fontWeight: 600, color: "var(--color-primary)" }}>
                      {bill.invoiceNumber || "N/A"}
                    </td>
                    <td data-label="Customer Phone">{bill.customerNumber}</td>
                    <td data-label="Total Amount" style={{ fontWeight: 600 }}>
                      ₹{bill.totalAmount.toFixed(2)}
                    </td>
                    <td data-label="Payment Method">
                      <span
                        style={{
                          textTransform: "capitalize",
                          fontSize: "0.75rem",
                          fontWeight: 600,
                          backgroundColor:
                            bill.paymentMethod === "cash"
                              ? "var(--color-accent-light)"
                              : bill.paymentMethod === "card"
                              ? "var(--color-primary-light)"
                              : "var(--color-success-light)",
                          color:
                            bill.paymentMethod === "cash"
                              ? "#B28800"
                              : bill.paymentMethod === "card"
                              ? "var(--color-primary)"
                              : "var(--color-success)",
                          padding: "2px 6px",
                          borderRadius: "4px"
                        }}
                      >
                        {bill.paymentMethod}
                      </span>
                    </td>
                    <td data-label="Accountant">{bill.accountant?.name || "Deleted User"}</td>
                    <td data-label="Created Date">
                      {new Date(bill.createdAt).toLocaleDateString("en-IN", {
                        day: "2-digit",
                        month: "short",
                        year: "numeric"
                      })}
                    </td>
                    <td data-label="Actions" style={{ textAlign: "center" }}>
                      <button
                        onClick={() => handleViewBill(bill)}
                        className="btn btn-ghost btn-sm"
                        title="View details"
                      >
                        <Eye size={16} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Table Pagination */}
          <div className="pagination">
            <span className="pagination-info">
              Showing <strong>{(page - 1) * limit + 1}</strong> to{" "}
              <strong>{Math.min(page * limit, filteredBills.length)}</strong> of{" "}
              <strong>{filteredBills.length}</strong> invoices
            </span>

            <div className="pagination-controls">
              <button
                onClick={() => setPage((prev) => Math.max(prev - 1, 1))}
                disabled={page === 1}
                className="btn btn-secondary btn-sm"
                style={{ padding: "6px 8px" }}
              >
                <ChevronLeft size={16} />
              </button>
              <span style={{ fontSize: "0.85rem", padding: "0 8px", fontWeight: 600 }}>
                Page {page} of {totalPages}
              </span>
              <button
                onClick={() => setPage((prev) => Math.min(prev + 1, totalPages))}
                disabled={page === totalPages}
                className="btn btn-secondary btn-sm"
                style={{ padding: "6px 8px" }}
              >
                <ChevronRight size={16} />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Invoice Details Preview Modal */}
      <Modal
        isOpen={isInvoiceOpen}
        onClose={() => setIsInvoiceOpen(false)}
        title="Invoice Receipt Preview"
        size="large"
        footer={
          <div style={{ display: "flex", gap: "10px", width: "100%", justifyContent: "flex-end" }}>
            <button onClick={handlePrint} className="btn btn-primary">
              <Printer size={16} />
              Print Receipt
            </button>
            <button onClick={() => setIsInvoiceOpen(false)} className="btn btn-secondary">
              Close
            </button>
          </div>
        }
      >
        {selectedBill && (
          <div className="print-invoice-sheet" style={{ padding: "10px", fontFamily: "var(--font-family)", color: "var(--color-text-primary)" }}>
            {/* Store Receipt Header */}
            <div style={{ textAlign: "center", borderBottom: "2px solid var(--color-border)", paddingBottom: "16px", marginBottom: "20px" }}>
              <div style={{ color: "var(--color-primary)", display: "flex", justifyContent: "center", marginBottom: "8px" }}>
                <Milk size={40} />
              </div>
              <h2 style={{ fontSize: "1.5rem", fontWeight: 700 }}>SRI SAI DAIRY PARLOUR</h2>
              <p style={{ fontSize: "0.85rem", color: "var(--color-text-secondary)" }}>Fresh Milk & Dairy Products Daily</p>
              <p style={{ fontSize: "0.85rem", color: "var(--color-text-secondary)" }}>123 Dairy Farm Avenue, Anand, Gujarat</p>
            </div>

            {/* Bill Meta Data */}
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px", marginBottom: "20px", fontSize: "0.875rem" }}>
              <div>
                <p><strong>Invoice Number:</strong> {selectedBill.invoiceNumber || "N/A"}</p>
                <p><strong>Customer Phone:</strong> {selectedBill.customerNumber}</p>
              </div>
              <div style={{ textAlign: "right" }}>
                <p>
                  <strong>Date:</strong>{" "}
                  {new Date(selectedBill.createdAt).toLocaleString("en-IN", {
                    day: "2-digit",
                    month: "short",
                    year: "numeric",
                    hour: "2-digit",
                    minute: "2-digit"
                  })}
                </p>
                <p><strong>Accountant:</strong> {selectedBill.accountant?.name || "Deleted User"}</p>
              </div>
            </div>

            {/* Invoice Products Table */}
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.875rem", marginBottom: "20px" }}>
              <thead>
                <tr style={{ borderBottom: "1px solid var(--color-text-primary)", textAlign: "left" }}>
                  <th style={{ padding: "6px 0" }}>Product Name</th>
                  <th style={{ padding: "6px 0", textAlign: "center" }}>Qty</th>
                  <th style={{ padding: "6px 0", textAlign: "right" }}>Unit Price</th>
                  <th style={{ padding: "6px 0", textAlign: "right" }}>Amount</th>
                </tr>
              </thead>
              <tbody>
                {selectedBill.products.map((item, index) => (
                  <tr key={index} style={{ borderBottom: "1px solid var(--color-border)" }}>
                    <td style={{ padding: "8px 0" }}>{item.product?.name || "Deleted Product"}</td>
                    <td style={{ padding: "8px 0", textAlign: "center" }}>{item.quantity}</td>
                    <td style={{ padding: "8px 0", textAlign: "right" }}>₹{(item.product?.price || 0).toFixed(2)}</td>
                    <td style={{ padding: "8px 0", textAlign: "right" }}>
                      ₹{((item.product?.price || 0) * item.quantity).toFixed(2)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {/* Total Section */}
            <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: "6px", fontSize: "0.875rem", borderTop: "2px solid var(--color-border)", paddingTop: "12px" }}>
              <div>
                <span>Subtotal: </span>
                <span style={{ width: "100px", display: "inline-block", textAlign: "right" }}>
                  ₹{selectedBill.totalAmount.toFixed(2)}
                </span>
              </div>
              <div style={{ fontSize: "1.125rem", fontWeight: 700 }}>
                <span>Grand Total: </span>
                <span style={{ width: "120px", display: "inline-block", textAlign: "right", color: "var(--color-primary)" }}>
                  ₹{selectedBill.totalAmount.toFixed(2)}
                </span>
              </div>
            </div>

            {/* Payment Details footer */}
            <div style={{ marginTop: "24px", borderTop: "1px dashed var(--color-border)", paddingTop: "12px", textAlign: "center", fontSize: "0.8rem", color: "var(--color-text-secondary)" }}>
              <p>Payment Mode: <strong style={{ textTransform: "uppercase", color: "var(--color-text-primary)" }}>{selectedBill.paymentMethod}</strong></p>
              <p style={{ marginTop: "8px" }}>Thank you for shopping at Sri Sai Dairy Parlour!</p>
              <p>Please visit us again.</p>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};

export default Bills;
